// Generated by gencpp from file srv_pkg/define.msg
// DO NOT EDIT!


#ifndef SRV_PKG_MESSAGE_DEFINE_H
#define SRV_PKG_MESSAGE_DEFINE_H

#include <ros/service_traits.h>


#include <srv_pkg/defineRequest.h>
#include <srv_pkg/defineResponse.h>


namespace srv_pkg
{

struct define
{

typedef defineRequest Request;
typedef defineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct define
} // namespace srv_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv_pkg::define > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::srv_pkg::define&) { return value(); }
};

template<>
struct DataType< ::srv_pkg::define > {
  static const char* value()
  {
    return "srv_pkg/define";
  }

  static const char* value(const ::srv_pkg::define&) { return value(); }
};


// service_traits::MD5Sum< ::srv_pkg::defineRequest> should match
// service_traits::MD5Sum< ::srv_pkg::define >
template<>
struct MD5Sum< ::srv_pkg::defineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv_pkg::define >::value();
  }
  static const char* value(const ::srv_pkg::defineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_pkg::defineRequest> should match
// service_traits::DataType< ::srv_pkg::define >
template<>
struct DataType< ::srv_pkg::defineRequest>
{
  static const char* value()
  {
    return DataType< ::srv_pkg::define >::value();
  }
  static const char* value(const ::srv_pkg::defineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv_pkg::defineResponse> should match
// service_traits::MD5Sum< ::srv_pkg::define >
template<>
struct MD5Sum< ::srv_pkg::defineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv_pkg::define >::value();
  }
  static const char* value(const ::srv_pkg::defineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv_pkg::defineResponse> should match
// service_traits::DataType< ::srv_pkg::define >
template<>
struct DataType< ::srv_pkg::defineResponse>
{
  static const char* value()
  {
    return DataType< ::srv_pkg::define >::value();
  }
  static const char* value(const ::srv_pkg::defineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_PKG_MESSAGE_DEFINE_H
