// Generated by gencpp from file define_msgs/Carry.msg
// DO NOT EDIT!


#ifndef DEFINE_MSGS_MESSAGE_CARRY_H
#define DEFINE_MSGS_MESSAGE_CARRY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace define_msgs
{
template <class ContainerAllocator>
struct Carry_
{
  typedef Carry_<ContainerAllocator> Type;

  Carry_()
    : grade()
    , star(0)
    , info()  {
    }
  Carry_(const ContainerAllocator& _alloc)
    : grade(_alloc)
    , star(0)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _grade_type;
  _grade_type grade;

   typedef int64_t _star_type;
  _star_type star;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::define_msgs::Carry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::define_msgs::Carry_<ContainerAllocator> const> ConstPtr;

}; // struct Carry_

typedef ::define_msgs::Carry_<std::allocator<void> > Carry;

typedef boost::shared_ptr< ::define_msgs::Carry > CarryPtr;
typedef boost::shared_ptr< ::define_msgs::Carry const> CarryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::define_msgs::Carry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::define_msgs::Carry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::define_msgs::Carry_<ContainerAllocator1> & lhs, const ::define_msgs::Carry_<ContainerAllocator2> & rhs)
{
  return lhs.grade == rhs.grade &&
    lhs.star == rhs.star &&
    lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::define_msgs::Carry_<ContainerAllocator1> & lhs, const ::define_msgs::Carry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace define_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::define_msgs::Carry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::define_msgs::Carry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::define_msgs::Carry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::define_msgs::Carry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::define_msgs::Carry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::define_msgs::Carry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::define_msgs::Carry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4563fd1b6e9431965973ee1f30e624f1";
  }

  static const char* value(const ::define_msgs::Carry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4563fd1b6e943196ULL;
  static const uint64_t static_value2 = 0x5973ee1f30e624f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::define_msgs::Carry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "define_msgs/Carry";
  }

  static const char* value(const ::define_msgs::Carry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::define_msgs::Carry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string grade\n"
"\n"
"int64 star\n"
"\n"
"string info\n"
;
  }

  static const char* value(const ::define_msgs::Carry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::define_msgs::Carry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grade);
      stream.next(m.star);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Carry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::define_msgs::Carry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::define_msgs::Carry_<ContainerAllocator>& v)
  {
    s << indent << "grade: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.grade);
    s << indent << "star: ";
    Printer<int64_t>::stream(s, indent + "  ", v.star);
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEFINE_MSGS_MESSAGE_CARRY_H
